Near unrestrained btc -> flo

diff --git a/scripts/debian/postinst b/scripts/debian/postinst
--- a/scripts/debian/postinst
+++ b/scripts/debian/postinst
@@ -3,35 +3,35 @@ set -e
 set -o pipefail
 
 # add group
-if ! getent group | grep -q "^bitcore:" ; then
-    echo "Creating system group: bitcore"
-    groupadd --system bitcore
+if ! getent group | grep -q "^flocore:" ; then
+    echo "Creating system group: flocore"
+    groupadd --system flocore
 fi
 
 # add user
-if ! getent passwd | grep -q "^bitcore:"; then
-    echo "Creating bitcore system user"
-    useradd --gid "bitcore" --system -m bitcore
+if ! getent passwd | grep -q "^flocore:"; then
+    echo "Creating flocore system user"
+    useradd --gid "flocore" --system -m flocore
 fi
 
 # build nodejs addons
-cd "/usr/opt/bitcore"
+cd "/usr/opt/flocore"
 SKIP_BITCOIN_DOWNLOAD=1 npm rebuild
 
 # setup data directory
-mkdir -p "/home/bitcore/.bitcore/data"
-chown -R bitcore:bitcore "/home/bitcore/.bitcore"
+mkdir -p "/home/flocore/.flocore/data"
+chown -R flocore:flocore "/home/flocore/.flocore"
 
-# start bitcore
+# start flocore
 if hash service 2> /dev/null; then
-    service bitcore start || echo "bitcore could not be registered or started"
+    service flocore start || echo "flocore could not be registered or started"
 elif hash start 2> /dev/null; then
-    start bitcore || echo "bitcore could not be registered or started"
+    start flocore || echo "flocore could not be registered or started"
 elif hash systemctl 2> /dev/null; then
     {
-        systemctl enable "bitcore.service" && \
-            systemctl start "bitcore.service"
-    } || echo "bitcore could not be registered or started"
+        systemctl enable "flocore.service" && \
+            systemctl start "flocore.service"
+    } || echo "flocore could not be registered or started"
 else
-    echo 'Your system does not appear to use upstart or systemd, so bitcore could not be started'
+    echo 'Your system does not appear to use upstart or systemd, so flocore could not be started'
 fi
